/* =========================================================================
   VITTA - Amplia catálogo com mais aparelhos/máquinas (idempotente)
   Adiciona exercícios de aparelhos comuns em academias brasileiras.
   Rode no SQL Editor do Supabase.
   ========================================================================= */

-- GLÚTEOS / QUADRÍCEPS / POSTERIOR (aparelhos)
INSERT INTO public.exercises (user_id, name, primary_muscle, secondary_muscles, equipment, substitutes, image_url, category, aliases, machine_type, laterality, difficulty, movement_pattern, instructions, common_mistakes)
VALUES
  (NULL, 'Cadeira abdutora', 'pernas', ARRAY['gluteos']::TEXT[], 'maquina', ARRAY[]::TEXT[], NULL, 'abdutores', ARRAY['Abdutora','Cadeira abdutora','Abduction']::TEXT[], 'selectorized', 'bilateral', 2, 'isolation', 'Sentado na máquina, abra as pernas contra a resistência. Retorne controlando.', 'Usar carga excessiva e balançar o tronco.'),
  (NULL, 'Cadeira adutora', 'pernas', ARRAY['gluteos']::TEXT[], 'maquina', ARRAY[]::TEXT[], NULL, 'adutores', ARRAY['Adutora','Cadeira adutora','Adduction']::TEXT[], 'selectorized', 'bilateral', 2, 'isolation', 'Sentado na máquina, feche as pernas contra a resistência. Retorne controlando.', 'Usar carga excessiva e abrir demais.'),
  (NULL, 'Mesa flexora unilateral', 'pernas', ARRAY['gluteos']::TEXT[], 'maquina', ARRAY[]::TEXT[], NULL, 'posterior', ARRAY['Flexora unilateral','Mesa flexora 1 perna']::TEXT[], 'selectorized', 'unilateral', 3, 'isolation', 'Deitado na mesa flexora, flexione um joelho por vez trazendo o calcanhar em direção ao glúteo.', 'Fazer movimento rápido demais e usar impulso.'),
  (NULL, 'Flexora em pé unilateral', 'pernas', ARRAY['gluteos']::TEXT[], 'maquina', ARRAY[]::TEXT[], NULL, 'posterior', ARRAY['Flexora em pé 1 perna','Flexora standing']::TEXT[], 'selectorized', 'unilateral', 3, 'isolation', 'Em pé no aparelho, flexione um joelho por vez trazendo o calcanhar em direção ao glúteo.', 'Usar o tronco para ajudar no movimento.'),
  (NULL, 'Extensão de quadril no cabo', 'pernas', ARRAY['gluteos']::TEXT[], 'cabo', ARRAY[]::TEXT[], NULL, 'gluteos', ARRAY['Cable hip extension','Extensão quadril polia']::TEXT[], 'cable', 'unilateral', 2, 'isolation', 'De costas para o cabo baixo, estenda o quadril levando a perna para trás.', 'Usar carga excessiva e hiperextender a lombar.'),
  (NULL, 'Agachamento no hack', 'pernas', ARRAY['gluteos']::TEXT[], 'maquina', ARRAY[]::TEXT[], NULL, 'quadriceps', ARRAY['Hack squat','Agachamento hack']::TEXT[], 'plate_loaded', 'bilateral', 3, 'compound', 'Posicione os ombros sob as almofadas e agache empurrando a plataforma.', 'Tirar os ombros do apoio e flexionar demais os joelhos.'),
  (NULL, 'Agachamento smith sumô', 'pernas', ARRAY['gluteos']::TEXT[], 'maquina', ARRAY[]::TEXT[], NULL, 'quadriceps', ARRAY['Smith sumô','Agachamento sumô smith']::TEXT[], 'smith', 'bilateral', 3, 'compound', 'Pés afastados na largura dos ombros, agache com os joelhos para fora.', 'Deixar os joelhos irem para dentro.'),
  (NULL, 'Leg press 45 unilateral', 'pernas', ARRAY['gluteos']::TEXT[], 'maquina', ARRAY[]::TEXT[], NULL, 'quadriceps', ARRAY['Leg press 1 perna','Leg press unilateral']::TEXT[], 'plate_loaded', 'unilateral', 3, 'compound', 'Posicione um pé na plataforma e empurre estendendo o joelho.', 'Usar carga excessiva e tirar o quadril do banco.'),
  (NULL, 'Stiff com halteres', 'pernas', ARRAY['gluteos']::TEXT[], 'haltere', ARRAY[]::TEXT[], NULL, 'posterior', ARRAY['Stiff halteres','Dumbbell stiff']::TEXT[], 'free_weight', 'bilateral', 3, 'compound', 'Segure os halteres à frente do corpo e incline o tronco à frente com os joelhos pouco flexionados.', 'Arredondar as costas e flexionar demais os joelhos.'),
  (NULL, 'Levantamento terra com halteres', 'pernas', ARRAY['gluteos']::TEXT[], 'haltere', ARRAY[]::TEXT[], NULL, 'posterior', ARRAY['Terra halteres','Dumbbell deadlift']::TEXT[], 'free_weight', 'bilateral', 3, 'compound', 'Segure os halteres à frente do corpo e incline o tronco à frente com os joelhos pouco flexionados.', 'Arredondar as costas e usar impulso.'),
  (NULL, 'Afundo com halteres', 'pernas', ARRAY['gluteos']::TEXT[], 'haltere', ARRAY[]::TEXT[], NULL, 'quadriceps', ARRAY['Afundo halteres','Avanço halteres']::TEXT[], 'free_weight', 'unilateral', 3, 'compound', 'Segure os halteres ao lado do corpo e dê um passo à frente flexionando os joelhos.', 'Deixar o joelho da frente ultrapassar a ponta do pé.'),
  (NULL, 'Step up com halteres', 'pernas', ARRAY['gluteos']::TEXT[], 'haltere', ARRAY[]::TEXT[], NULL, 'quadriceps', ARRAY['Step up halteres','Subida step halteres']::TEXT[], 'free_weight', 'unilateral', 3, 'compound', 'Segure os halteres e suba em um banco ou step, empurrando com a perna da frente.', 'Usar a perna de trás para impulsionar.'),
  (NULL, 'Agachamento búlgaro com halteres', 'pernas', ARRAY['gluteos']::TEXT[], 'haltere', ARRAY[]::TEXT[], NULL, 'quadriceps', ARRAY['Búlgaro halteres','Afundo búlgaro halteres']::TEXT[], 'free_weight', 'unilateral', 4, 'compound', 'Posicione um pé atrás de você em um banco e agache com a perna da frente.', 'Deixar o joelho da frente ultrapassar a ponta do pé.'),
  (NULL, 'Ponte de glúteo com barra', 'pernas', ARRAY['gluteos']::TEXT[], 'barra', ARRAY[]::TEXT[], NULL, 'gluteos', ARRAY['Hip thrust barra','Ponte glúteo barra']::TEXT[], 'free_weight', 'bilateral', 3, 'compound', 'Deitado com a barra sobre o quadril, eleve o quadril contraindo os glúteos.', 'Hiperextender a lombar no topo.'),
  (NULL, 'Ponte de glúteo com halteres', 'pernas', ARRAY['gluteos']::TEXT[], 'haltere', ARRAY[]::TEXT[], NULL, 'gluteos', ARRAY['Hip thrust halteres','Ponte glúteo halteres']::TEXT[], 'free_weight', 'bilateral', 2, 'compound', 'Deitado com um halter sobre o quadril, eleve o quadril contraindo os glúteos.', 'Hiperextender a lombar no topo.'),
  (NULL, 'Coice com elástico', 'pernas', ARRAY['gluteos']::TEXT[], 'elastico', ARRAY[]::TEXT[], NULL, 'gluteos', ARRAY['Kickback elástico','Coice elástico']::TEXT[], 'cable', 'unilateral', 2, 'isolation', 'De quatro apoios com elástico no tornozelo, estenda a perna para trás contraindo o glúteo.', 'Usar impulso e hiperextender a lombar.'),
  (NULL, 'Abdução de quadril com elástico', 'pernas', ARRAY['gluteos']::TEXT[], 'elastico', ARRAY[]::TEXT[], NULL, 'abdutores', ARRAY['Abdução elástico','Abdução quadril elástico']::TEXT[], 'cable', 'unilateral', 2, 'isolation', 'De lado com elástico no tornozelo, abra a perna contra a resistência.', 'Usar impulso e inclinar o tronco.'),
  (NULL, 'Agachamento com elástico', 'pernas', ARRAY['gluteos']::TEXT[], 'elastico', ARRAY[]::TEXT[], NULL, 'quadriceps', ARRAY['Agachamento elástico','Squat elástico']::TEXT[], 'cable', 'bilateral', 2, 'compound', 'Com elástico nos joelhos, agache empurrando os joelhos para fora.', 'Deixar os joelhos irem para dentro.'),
  (NULL, 'Caminhada com elástico', 'pernas', ARRAY['gluteos']::TEXT[], 'elastico', ARRAY[]::TEXT[], NULL, 'gluteos', ARRAY['Caminhada elástico','Monster walk']::TEXT[], 'cable', 'bilateral', 2, 'compound', 'Com elástico nos tornozelos, dê passos laterais mantendo a tensão.', 'Deixar o elástico frouxo e usar impulso.'),
  (NULL, 'Agachamento com kettlebell', 'pernas', ARRAY['gluteos']::TEXT[], 'kettlebell', ARRAY[]::TEXT[], NULL, 'quadriceps', ARRAY['Goblet squat','Agachamento kettlebell']::TEXT[], 'free_weight', 'bilateral', 3, 'compound', 'Segure o kettlebell contra o peito e agache.', 'Deixar os joelhos irem para dentro e arredondar as costas.'),
  (NULL, 'Swing de kettlebell', 'pernas', ARRAY['gluteos']::TEXT[], 'kettlebell', ARRAY[]::TEXT[], NULL, 'posterior', ARRAY['Kettlebell swing','Swing kettlebell']::TEXT[], 'free_weight', 'bilateral', 3, 'compound', 'Segure o kettlebell com as duas mãos e balance entre as pernas estendendo o quadril.', 'Usar os braços para levantar e hiperextender a lombar.'),
  (NULL, 'Stiff com kettlebell', 'pernas', ARRAY['gluteos']::TEXT[], 'kettlebell', ARRAY[]::TEXT[], NULL, 'posterior', ARRAY['Stiff kettlebell','Kettlebell stiff']::TEXT[], 'free_weight', 'bilateral', 3, 'compound', 'Segure o kettlebell à frente do corpo e incline o tronco à frente com os joelhos pouco flexionados.', 'Arredondar as costas e flexionar demais os joelhos.'),

-- PEITO (aparelhos)
  (NULL, 'Supino reto com barra', 'peito', ARRAY['triceps','ombros']::TEXT[], 'barra', ARRAY[]::TEXT[], NULL, 'peito', ARRAY['Supino barra','Bench press']::TEXT[], 'free_weight', 'bilateral', 3, 'compound', 'Deitado no banco, desça a barra até o peito e empurre estendendo os cotovelos.', 'Tirar os pés do chão e arquear demais as costas.'),
  (NULL, 'Supino inclinado com barra', 'peito', ARRAY['triceps','ombros']::TEXT[], 'barra', ARRAY[]::TEXT[], NULL, 'peito', ARRAY['Supino inclinado barra','Incline bench press']::TEXT[], 'free_weight', 'bilateral', 3, 'compound', 'Deitado no banco inclinado, desça a barra até o peito e empurre estendendo os cotovelos.', 'Tirar os pés do chão e usar impulso.'),
  (NULL, 'Supino reto com halteres', 'peito', ARRAY['triceps','ombros']::TEXT[], 'haltere', ARRAY[]::TEXT[], NULL, 'peito', ARRAY['Supino halteres','Dumbbell bench press']::TEXT[], 'free_weight', 'bilateral', 3, 'compound', 'Deitado no banco, desça os halteres até o peito e empurre estendendo os cotovelos.', 'Usar carga excessiva e tirar os pés do chão.'),
  (NULL, 'Supino inclinado com halteres', 'peito', ARRAY['triceps','ombros']::TEXT[], 'haltere', ARRAY[]::TEXT[], NULL, 'peito', ARRAY['Supino inclinado halteres','Incline dumbbell press']::TEXT[], 'free_weight', 'bilateral', 3, 'compound', 'Deitado no banco inclinado, desça os halteres até o peito e empurre estendendo os cotovelos.', 'Usar carga excessiva e tirar os pés do chão.'),
  (NULL, 'Crucifixo reto com halteres', 'peito', ARRAY[]::TEXT[], 'haltere', ARRAY[]::TEXT[], NULL, 'peito', ARRAY['Crucifixo halteres','Dumbbell fly']::TEXT[], 'free_weight', 'bilateral', 2, 'isolation', 'Deitado no banco, abra os halteres para os lados com os cotovelos pouco flexionados.', 'Usar carga excessiva e flexionar demais os cotovelos.'),
  (NULL, 'Crucifixo inclinado com halteres', 'peito', ARRAY[]::TEXT[], 'haltere', ARRAY[]::TEXT[], NULL, 'peito', ARRAY['Crucifixo inclinado halteres','Incline dumbbell fly']::TEXT[], 'free_weight', 'bilateral', 2, 'isolation', 'Deitado no banco inclinado, abra os halteres para os lados com os cotovelos pouco flexionados.', 'Usar carga excessiva e flexionar demais os cotovelos.'),
  (NULL, 'Crucifixo no cabo', 'peito', ARRAY[]::TEXT[], 'cabo', ARRAY[]::TEXT[], NULL, 'peito', ARRAY['Cable fly','Crucifixo polia']::TEXT[], 'cable', 'bilateral', 2, 'isolation', 'Em pé entre as polias, abra os cabos para os lados com os cotovelos pouco flexionados.', 'Usar carga excessiva e usar impulso.'),
  (NULL, 'Crucifixo no crossover', 'peito', ARRAY[]::TEXT[], 'maquina', ARRAY[]::TEXT[], NULL, 'peito', ARRAY['Crossover','Crucifixo crossover']::TEXT[], 'cable', 'bilateral', 2, 'isolation', 'Em pé no crossover, abra os cabos para os lados com os cotovelos pouco flexionados.', 'Usar carga excessiva e usar impulso.'),
  (NULL, 'Supino no smith', 'peito', ARRAY['triceps','ombros']::TEXT[], 'maquina', ARRAY[]::TEXT[], NULL, 'peito', ARRAY['Smith supino','Supino smith']::TEXT[], 'smith', 'bilateral', 3, 'compound', 'Deitado no banco, desça a barra até o peito e empurre estendendo os cotovelos.', 'Tirar os pés do chão e usar impulso.'),
  (NULL, 'Supino inclinado no smith', 'peito', ARRAY['triceps','ombros']::TEXT[], 'maquina', ARRAY[]::TEXT[], NULL, 'peito', ARRAY['Smith supino inclinado','Supino inclinado smith']::TEXT[], 'smith', 'bilateral', 3, 'compound', 'Deitado no banco inclinado, desça a barra até o peito e empurre estendendo os cotovelos.', 'Tirar os pés do chão e usar impulso.'),
  (NULL, 'Flexão de braço', 'peito', ARRAY['triceps','core']::TEXT[], 'nenhum', ARRAY[]::TEXT[], NULL, 'peito', ARRAY['Flexão','Push up']::TEXT[], 'bodyweight', 'bilateral', 2, 'compound', 'Em posição de prancha, desça o corpo até o peito quase tocar o chão e empurre estendendo os cotovelos.', 'Deixar o quadril cair e usar impulso.'),
  (NULL, 'Flexão de braço inclinada', 'peito', ARRAY['triceps','core']::TEXT[], 'nenhum', ARRAY[]::TEXT[], NULL, 'peito', ARRAY['Flexão inclinada','Push up inclinado']::TEXT[], 'bodyweight', 'bilateral', 1, 'compound', 'Com as mãos em um banco, desça o corpo até o peito quase tocar o banco e empurre estendendo os cotovelos.', 'Deixar o quadril cair e usar impulso.'),
  (NULL, 'Flexão de braço declinada', 'peito', ARRAY['triceps','core']::TEXT[], 'nenhum', ARRAY[]::TEXT[], NULL, 'peito', ARRAY['Flexão declinada','Push up declinado']::TEXT[], 'bodyweight', 'bilateral', 3, 'compound', 'Com os pés em um banco, desça o corpo até o peito quase tocar o chão e empurre estendendo os cotovelos.', 'Deixar o quadril cair e usar impulso.'),
  (NULL, 'Mergulho entre bancos', 'peito', ARRAY['triceps','ombros']::TEXT[], 'nenhum', ARRAY[]::TEXT[], NULL, 'peito', ARRAY['Dips','Mergulho']::TEXT[], 'bodyweight', 'bilateral', 3, 'compound', 'Entre dois bancos, desça o corpo flexionando os cotovelos e empurre estendendo os cotovelos.', 'Usar impulso e flexionar demais os ombros.'),

-- COSTAS (aparelhos)
  (NULL, 'Puxador alto', 'costas', ARRAY['biceps']::TEXT[], 'maquina', ARRAY[]::TEXT[], NULL, 'costas', ARRAY['Lat pulldown','Puxador']::TEXT[], 'cable', 'bilateral', 2, 'compound', 'Sentado no puxador, puxe a barra até o peito com os cotovelos para baixo.', 'Usar impulso e puxar atrás do pescoço.'),
  (NULL, 'Puxador alto com pegada neutra', 'costas', ARRAY['biceps']::TEXT[], 'maquina', ARRAY[]::TEXT[], NULL, 'costas', ARRAY['Puxador neutro','Lat pulldown neutro']::TEXT[], 'cable', 'bilateral', 2, 'compound', 'Sentado no puxador com pegada neutra, puxe a barra até o peito com os cotovelos para baixo.', 'Usar impulso e puxar atrás do pescoço.'),
  (NULL, 'Puxador alto com pegada supinada', 'costas', ARRAY['biceps']::TEXT[], 'maquina', ARRAY[]::TEXT[], NULL, 'costas', ARRAY['Puxador supinado','Lat pulldown supinado']::TEXT[], 'cable', 'bilateral', 2, 'compound', 'Sentado no puxador com pegada supinada, puxe a barra até o peito com os cotovelos para baixo.', 'Usar impulso e puxar atrás do pescoço.'),
  (NULL, 'Remada sentada no cabo', 'costas', ARRAY['biceps']::TEXT[], 'cabo', ARRAY[]::TEXT[], NULL, 'costas', ARRAY['Remada cabo','Seated cable row']::TEXT[], 'cable', 'bilateral', 2, 'compound', 'Sentado no cabo, puxe a alça até o abdômen com os cotovelos para trás.', 'Usar impulso e puxar com os ombros.'),
  (NULL, 'Remada sentada com pegada neutra', 'costas', ARRAY['biceps']::TEXT[], 'cabo', ARRAY[]::TEXT[], NULL, 'costas', ARRAY['Remada neutra','Seated cable row neutro']::TEXT[], 'cable', 'bilateral', 2, 'compound', 'Sentado no cabo com pegada neutra, puxe a alça até o abdômen com os cotovelos para trás.', 'Usar impulso e puxar com os ombros.'),
  (NULL, 'Remada unilateral com haltere', 'costas', ARRAY['biceps']::TEXT[], 'haltere', ARRAY[]::TEXT[], NULL, 'costas', ARRAY['Remada haltere','One arm dumbbell row']::TEXT[], 'free_weight', 'unilateral', 2, 'compound', 'Com uma mão e um joelho no banco, puxe o haltere até o quadril com o cotovelo para trás.', 'Usar impulso e girar o tronco.'),
  (NULL, 'Remada curvada com barra', 'costas', ARRAY['biceps']::TEXT[], 'barra', ARRAY[]::TEXT[], NULL, 'costas', ARRAY['Remada curvada','Bent over row']::TEXT[], 'free_weight', 'bilateral', 3, 'compound', 'Inclinado à frente, puxe a barra até o abdômen com os cotovelos para trás.', 'Arredondar as costas e usar impulso.'),
  (NULL, 'Remada curvada com halteres', 'costas', ARRAY['biceps']::TEXT[], 'haltere', ARRAY[]::TEXT[], NULL, 'costas', ARRAY['Remada curvada halteres','Bent over dumbbell row']::TEXT[], 'free_weight', 'bilateral', 3, 'compound', 'Inclinado à frente, puxe os halteres até o abdômen com os cotovelos para trás.', 'Arredondar as costas e usar impulso.'),
  (NULL, 'Remada no smith', 'costas', ARRAY['biceps']::TEXT[], 'maquina', ARRAY[]::TEXT[], NULL, 'costas', ARRAY['Smith remada','Remada smith']::TEXT[], 'smith', 'bilateral', 3, 'compound', 'Inclinado à frente, puxe a barra até o abdômen com os cotovelos para trás.', 'Arredondar as costas e usar impulso.'),
  (NULL, 'Pullover com haltere', 'costas', ARRAY['peito']::TEXT[], 'haltere', ARRAY[]::TEXT[], NULL, 'costas', ARRAY['Pullover','Pullover haltere']::TEXT[], 'free_weight', 'bilateral', 2, 'isolation', 'Deitado no banco, segure um haltere com as duas mãos e leve-o para trás da cabeça.', 'Usar carga excessiva e flexionar demais os cotovelos.'),
  (NULL, 'Pullover no cabo', 'costas', ARRAY['peito']::TEXT[], 'cabo', ARRAY[]::TEXT[], NULL, 'costas', ARRAY['Pullover cabo','Cable pullover']::TEXT[], 'cable', 'bilateral', 2, 'isolation', 'Deitado no banco, segure a alça do cabo e leve-a para trás da cabeça.', 'Usar carga excessiva e flexionar demais os cotovelos.'),
  (NULL, 'Barra fixa', 'costas', ARRAY['biceps']::TEXT[], 'nenhum', ARRAY[]::TEXT[], NULL, 'costas', ARRAY['Pull up','Barra fixa']::TEXT[], 'bodyweight', 'bilateral', 4, 'compound', 'Segure a barra com pegada pronada e puxe o corpo até o queixo passar a barra.', 'Usar impulso e puxar com os ombros.'),
  (NULL, 'Barra fixa com pegada supinada', 'costas', ARRAY['biceps']::TEXT[], 'nenhum', ARRAY[]::TEXT[], NULL, 'costas', ARRAY['Chin up','Barra fixa supinada']::TEXT[], 'bodyweight', 'bilateral', 4, 'compound', 'Segure a barra com pegada supinada e puxe o corpo até o queixo passar a barra.', 'Usar impulso e puxar com os ombros.'),
  (NULL, 'Barra fixa com pegada neutra', 'costas', ARRAY['biceps']::TEXT[], 'nenhum', ARRAY[]::TEXT[], NULL, 'costas', ARRAY['Pull up neutro','Barra fixa neutra']::TEXT[], 'bodyweight', 'bilateral', 4, 'compound', 'Segure a barra com pegada neutra e puxe o corpo até o queixo passar a barra.', 'Usar impulso e puxar com os ombros.'),
  (NULL, 'Remada baixa no cabo', 'costas', ARRAY['biceps']::TEXT[], 'cabo', ARRAY[]::TEXT[], NULL, 'costas', ARRAY['Remada baixa','Low cable row']::TEXT[], 'cable', 'bilateral', 2, 'compound', 'Sentado no cabo baixo, puxe a alça até o abdômen com os cotovelos para trás.', 'Usar impulso e puxar com os ombros.'),

-- OMBROS (aparelhos)
  (NULL, 'Desenvolvimento com halteres', 'ombros', ARRAY['triceps']::TEXT[], 'haltere', ARRAY[]::TEXT[], NULL, 'ombros', ARRAY['Desenvolvimento halteres','Dumbbell shoulder press']::TEXT[], 'free_weight', 'bilateral', 3, 'compound', 'Sentado, empurre os halteres para cima estendendo os cotovelos.', 'Usar impulso e hiperextender a lombar.'),
  (NULL, 'Desenvolvimento com barra', 'ombros', ARRAY['triceps']::TEXT[], 'barra', ARRAY[]::TEXT[], NULL, 'ombros', ARRAY['Desenvolvimento barra','Barbell shoulder press']::TEXT[], 'free_weight', 'bilateral', 3, 'compound', 'Em pé, empurre a barra para cima estendendo os cotovelos.', 'Usar impulso e hiperextender a lombar.'),
  (NULL, 'Desenvolvimento no smith', 'ombros', ARRAY['triceps']::TEXT[], 'maquina', ARRAY[]::TEXT[], NULL, 'ombros', ARRAY['Smith desenvolvimento','Desenvolvimento smith']::TEXT[], 'smith', 'bilateral', 3, 'compound', 'Sentado, empurre a barra para cima estendendo os cotovelos.', 'Usar impulso e hiperextender a lombar.'),
  (NULL, 'Elevação lateral com halteres', 'ombros', ARRAY[]::TEXT[], 'haltere', ARRAY[]::TEXT[], NULL, 'ombros', ARRAY['Elevação lateral','Lateral raise']::TEXT[], 'free_weight', 'bilateral', 2, 'isolation', 'Em pé, eleve os halteres para os lados até a altura dos ombros.', 'Usar impulso e elevar demais.'),
  (NULL, 'Elevação lateral no cabo', 'ombros', ARRAY[]::TEXT[], 'cabo', ARRAY[]::TEXT[], NULL, 'ombros', ARRAY['Elevação lateral cabo','Cable lateral raise']::TEXT[], 'cable', 'unilateral', 2, 'isolation', 'De lado para o cabo, eleve a alça para o lado até a altura do ombro.', 'Usar impulso e elevar demais.'),
  (NULL, 'Elevação frontal com halteres', 'ombros', ARRAY[]::TEXT[], 'haltere', ARRAY[]::TEXT[], NULL, 'ombros', ARRAY['Elevação frontal','Front raise']::TEXT[], 'free_weight', 'bilateral', 2, 'isolation', 'Em pé, eleve os halteres para frente até a altura dos ombros.', 'Usar impulso e elevar demais.'),
  (NULL, 'Elevação frontal no cabo', 'ombros', ARRAY[]::TEXT[], 'cabo', ARRAY[]::TEXT[], NULL, 'ombros', ARRAY['Elevação frontal cabo','Cable front raise']::TEXT[], 'cable', 'unilateral', 2, 'isolation', 'De costas para o cabo, eleve a alça para frente até a altura do ombro.', 'Usar impulso e elevar demais.'),
  (NULL, 'Crucifixo invertido com halteres', 'ombros', ARRAY[]::TEXT[], 'haltere', ARRAY[]::TEXT[], NULL, 'ombros', ARRAY['Crucifixo invertido','Reverse fly']::TEXT[], 'free_weight', 'bilateral', 2, 'isolation', 'Inclinado à frente, abra os halteres para os lados com os cotovelos pouco flexionados.', 'Usar carga excessiva e usar impulso.'),
  (NULL, 'Crucifixo invertido no cabo', 'ombros', ARRAY[]::TEXT[], 'cabo', ARRAY[]::TEXT[], NULL, 'ombros', ARRAY['Crucifixo invertido cabo','Cable reverse fly']::TEXT[], 'cable', 'bilateral', 2, 'isolation', 'Em pé entre as polias, abra os cabos para os lados com os cotovelos pouco flexionados.', 'Usar carga excessiva e usar impulso.'),
  (NULL, 'Encolhimento com halteres', 'ombros', ARRAY[]::TEXT[], 'haltere', ARRAY[]::TEXT[], NULL, 'ombros', ARRAY['Encolhimento','Shrug']::TEXT[], 'free_weight', 'bilateral', 2, 'isolation', 'Em pé, eleve os ombros em direção às orelhas segurando os halteres.', 'Usar impulso e flexionar o pescoço.'),
  (NULL, 'Encolhimento com barra', 'ombros', ARRAY[]::TEXT[], 'barra', ARRAY[]::TEXT[], NULL, 'ombros', ARRAY['Encolhimento barra','Barbell shrug']::TEXT[], 'free_weight', 'bilateral', 2, 'isolation', 'Em pé, eleve os ombros em direção às orelhas segurando a barra.', 'Usar impulso e flexionar o pescoço.'),
  (NULL, 'Desenvolvimento arnold', 'ombros', ARRAY['triceps']::TEXT[], 'haltere', ARRAY[]::TEXT[], NULL, 'ombros', ARRAY['Arnold press','Desenvolvimento arnold']::TEXT[], 'free_weight', 'bilateral', 3, 'compound', 'Sentado, empurre os halteres para cima girando as palmas para frente.', 'Usar impulso e hiperextender a lombar.'),

-- BÍCEPS (aparelhos)
  (NULL, 'Rosca direta com barra', 'bracos', ARRAY[]::TEXT[], 'barra', ARRAY[]::TEXT[], NULL, 'biceps', ARRAY['Rosca barra','Barbell curl']::TEXT[], 'free_weight', 'bilateral', 2, 'isolation', 'Em pé, flexione os cotovelos levando a barra até os ombros.', 'Usar impulso e flexionar os ombros.'),
  (NULL, 'Rosca direta com halteres', 'bracos', ARRAY[]::TEXT[], 'haltere', ARRAY[]::TEXT[], NULL, 'biceps', ARRAY['Rosca halteres','Dumbbell curl']::TEXT[], 'free_weight', 'bilateral', 2, 'isolation', 'Em pé, flexione os cotovelos levando os halteres até os ombros.', 'Usar impulso e flexionar os ombros.'),
  (NULL, 'Rosca alternada com halteres', 'bracos', ARRAY[]::TEXT[], 'haltere', ARRAY[]::TEXT[], NULL, 'biceps', ARRAY['Rosca alternada','Alternating dumbbell curl']::TEXT[], 'free_weight', 'unilateral', 2, 'isolation', 'Em pé, flexione um cotovelo por vez levando o haltere até o ombro.', 'Usar impulso e flexionar os ombros.'),
  (NULL, 'Rosca concentrada', 'bracos', ARRAY[]::TEXT[], 'haltere', ARRAY[]::TEXT[], NULL, 'biceps', ARRAY['Rosca concentrada','Concentration curl']::TEXT[], 'free_weight', 'unilateral', 2, 'isolation', 'Sentado, apoie o cotovelo na coxa e flexione o cotovelo levando o haltere até o ombro.', 'Usar impulso e flexionar os ombros.'),
  (NULL, 'Rosca scott com barra', 'bracos', ARRAY[]::TEXT[], 'maquina', ARRAY[]::TEXT[], NULL, 'biceps', ARRAY['Rosca scott','Preacher curl']::TEXT[], 'free_weight', 'bilateral', 2, 'isolation', 'Apoie os braços no banco scott e flexione os cotovelos levando a barra até os ombros.', 'Usar impulso e tirar os braços do banco.'),
  (NULL, 'Rosca scott com halteres', 'bracos', ARRAY[]::TEXT[], 'maquina', ARRAY[]::TEXT[], NULL, 'biceps', ARRAY['Rosca scott halteres','Preacher curl halteres']::TEXT[], 'free_weight', 'bilateral', 2, 'isolation', 'Apoie os braços no banco scott e flexione os cotovelos levando os halteres até os ombros.', 'Usar impulso e tirar os braços do banco.'),
  (NULL, 'Rosca no cabo', 'bracos', ARRAY[]::TEXT[], 'cabo', ARRAY[]::TEXT[], NULL, 'biceps', ARRAY['Rosca cabo','Cable curl']::TEXT[], 'cable', 'bilateral', 2, 'isolation', 'Em pé, flexione os cotovelos levando a alça do cabo até os ombros.', 'Usar impulso e flexionar os ombros.'),
  (NULL, 'Rosca no cabo com corda', 'bracos', ARRAY[]::TEXT[], 'cabo', ARRAY[]::TEXT[], NULL, 'biceps', ARRAY['Rosca corda','Cable curl corda']::TEXT[], 'cable', 'bilateral', 2, 'isolation', 'Em pé, flexione os cotovelos levando a corda até os ombros.', 'Usar impulso e flexionar os ombros.'),
  (NULL, 'Rosca martelo com halteres', 'bracos', ARRAY[]::TEXT[], 'haltere', ARRAY[]::TEXT[], NULL, 'biceps', ARRAY['Rosca martelo','Hammer curl']::TEXT[], 'free_weight', 'bilateral', 2, 'isolation', 'Em pé, flexione os cotovelos levando os halteres até os ombros com pegada neutra.', 'Usar impulso e flexionar os ombros.'),
  (NULL, 'Rosca martelo no cabo', 'bracos', ARRAY[]::TEXT[], 'cabo', ARRAY[]::TEXT[], NULL, 'biceps', ARRAY['Rosca martelo cabo','Hammer curl cabo']::TEXT[], 'cable', 'bilateral', 2, 'isolation', 'Em pé, flexione os cotovelos levando a corda até os ombros com pegada neutra.', 'Usar impulso e flexionar os ombros.'),
  (NULL, 'Rosca inversa com barra', 'bracos', ARRAY[]::TEXT[], 'barra', ARRAY[]::TEXT[], NULL, 'biceps', ARRAY['Rosca inversa','Reverse curl']::TEXT[], 'free_weight', 'bilateral', 2, 'isolation', 'Em pé, flexione os cotovelos levando a barra até os ombros com pegada pronada.', 'Usar impulso e flexionar os ombros.'),

-- TRÍCEPS (aparelhos)
  (NULL, 'Tríceps testa com barra', 'bracos', ARRAY[]::TEXT[], 'barra', ARRAY[]::TEXT[], NULL, 'triceps', ARRAY['Tríceps testa','Skull crusher']::TEXT[], 'free_weight', 'bilateral', 2, 'isolation', 'Deitado no banco, estenda os cotovelos levando a barra até acima da testa.', 'Usar carga excessiva e abrir os cotovelos.'),
  (NULL, 'Tríceps testa com halteres', 'bracos', ARRAY[]::TEXT[], 'haltere', ARRAY[]::TEXT[], NULL, 'triceps', ARRAY['Tríceps testa halteres','Skull crusher halteres']::TEXT[], 'free_weight', 'bilateral', 2, 'isolation', 'Deitado no banco, estenda os cotovelos levando os halteres até acima da testa.', 'Usar carga excessiva e abrir os cotovelos.'),
  (NULL, 'Tríceps no cabo', 'bracos', ARRAY[]::TEXT[], 'cabo', ARRAY[]::TEXT[], NULL, 'triceps', ARRAY['Tríceps cabo','Cable triceps pushdown']::TEXT[], 'cable', 'bilateral', 2, 'isolation', 'Em pé, estenda os cotovelos levando a alça do cabo para baixo.', 'Usar impulso e abrir os cotovelos.'),
  (NULL, 'Tríceps no cabo com corda', 'bracos', ARRAY[]::TEXT[], 'cabo', ARRAY[]::TEXT[], NULL, 'triceps', ARRAY['Tríceps corda','Cable triceps corda']::TEXT[], 'cable', 'bilateral', 2, 'isolation', 'Em pé, estenda os cotovelos levando a corda para baixo.', 'Usar impulso e abrir os cotovelos.'),
  (NULL, 'Tríceps mergulho', 'bracos', ARRAY['peito']::TEXT[], 'nenhum', ARRAY[]::TEXT[], NULL, 'triceps', ARRAY['Mergulho','Dips']::TEXT[], 'bodyweight', 'bilateral', 3, 'compound', 'Entre dois bancos, desça o corpo flexionando os cotovelos e empurre estendendo os cotovelos.', 'Usar impulso e flexionar demais os ombros.'),
  (NULL, 'Tríceps coice com haltere', 'bracos', ARRAY[]::TEXT[], 'haltere', ARRAY[]::TEXT[], NULL, 'triceps', ARRAY['Tríceps coice','Triceps kickback']::TEXT[], 'free_weight', 'unilateral', 2, 'isolation', 'Inclinado à frente, estenda o cotovelo levando o haltere para trás.', 'Usar impulso e abrir o cotovelo.'),
  (NULL, 'Tríceps coice no cabo', 'bracos', ARRAY[]::TEXT[], 'cabo', ARRAY[]::TEXT[], NULL, 'triceps', ARRAY['Tríceps coice cabo','Cable triceps kickback']::TEXT[], 'cable', 'unilateral', 2, 'isolation', 'Inclinado à frente, estenda o cotovelo levando a alça do cabo para trás.', 'Usar impulso e abrir o cotovelo.'),
  (NULL, 'Supino fechado com barra', 'bracos', ARRAY['peito']::TEXT[], 'barra', ARRAY[]::TEXT[], NULL, 'triceps', ARRAY['Supino fechado','Close grip bench press']::TEXT[], 'free_weight', 'bilateral', 3, 'compound', 'Deitado no banco, desça a barra até o peito com pegada fechada e empurre estendendo os cotovelos.', 'Usar carga excessiva e abrir os cotovelos.'),
  (NULL, 'Supino fechado com halteres', 'bracos', ARRAY['peito']::TEXT[], 'haltere', ARRAY[]::TEXT[], NULL, 'triceps', ARRAY['Supino fechado halteres','Close grip dumbbell press']::TEXT[], 'free_weight', 'bilateral', 3, 'compound', 'Deitado no banco, desça os halteres até o peito com pegada fechada e empurre estendendo os cotovelos.', 'Usar carga excessiva e abrir os cotovelos.'),

-- CORE / ABDOMEN (aparelhos)
  (NULL, 'Prancha isométrica', 'core', ARRAY[]::TEXT[], 'nenhum', ARRAY[]::TEXT[], NULL, 'abdomen', ARRAY['Prancha','Plank']::TEXT[], 'bodyweight', 'bilateral', 2, 'isolation', 'Em posição de prancha, mantenha o corpo reto contraindo o abdômen.', 'Deixar o quadril cair ou subir demais.'),
  (NULL, 'Prancha lateral', 'core', ARRAY[]::TEXT[], 'nenhum', ARRAY[]::TEXT[], NULL, 'abdomen', ARRAY['Prancha lateral','Side plank']::TEXT[], 'bodyweight', 'unilateral', 2, 'isolation', 'De lado, apoie o antebraço no chão e mantenha o corpo reto.', 'Deixar o quadril cair e usar impulso.'),
  (NULL, 'Abdominal crunch', 'core', ARRAY[]::TEXT[], 'nenhum', ARRAY[]::TEXT[], NULL, 'abdomen', ARRAY['Crunch','Abdominal']::TEXT[], 'bodyweight', 'bilateral', 1, 'isolation', 'Deitado, flexione o tronco levando os ombros em direção ao quadril.', 'Usar impulso e puxar o pescoço.'),
  (NULL, 'Abdominal no cabo', 'core', ARRAY[]::TEXT[], 'cabo', ARRAY[]::TEXT[], NULL, 'abdomen', ARRAY['Cable crunch','Abdominal cabo']::TEXT[], 'cable', 'bilateral', 2, 'isolation', 'De joelhos, flexione o tronco levando os cotovelos em direção aos joelhos.', 'Usar impulso e puxar com os braços.'),
  (NULL, 'Abdominal na máquina', 'core', ARRAY[]::TEXT[], 'maquina', ARRAY[]::TEXT[], NULL, 'abdomen', ARRAY['Machine crunch','Abdominal máquina']::TEXT[], 'selectorized', 'bilateral', 2, 'isolation', 'Sentado na máquina, flexione o tronco levando os ombros em direção ao quadril.', 'Usar impulso e puxar com os braços.'),
  (NULL, 'Elevação de pernas', 'core', ARRAY[]::TEXT[], 'nenhum', ARRAY[]::TEXT[], NULL, 'abdomen', ARRAY['Leg raise','Elevação pernas']::TEXT[], 'bodyweight', 'bilateral', 2, 'isolation', 'Deitado, eleve as pernas estendidas até a vertical.', 'Usar impulso e dobrar os joelhos.'),
  (NULL, 'Elevação de pernas na barra', 'core', ARRAY[]::TEXT[], 'nenhum', ARRAY[]::TEXT[], NULL, 'abdomen', ARRAY['Hanging leg raise','Elevação pernas barra']::TEXT[], 'bodyweight', 'bilateral', 3, 'isolation', 'Pendurado na barra, eleve as pernas estendidas até a vertical.', 'Usar impulso e balançar o corpo.'),
  (NULL, 'Russian twist', 'core', ARRAY[]::TEXT[], 'nenhum', ARRAY[]::TEXT[], NULL, 'abdomen', ARRAY['Russian twist','Twist russo']::TEXT[], 'bodyweight', 'bilateral', 2, 'isolation', 'Sentado com os pés elevados, gire o tronco para os lados.', 'Usar impulso e girar só os braços.'),
  (NULL, 'Russian twist com haltere', 'core', ARRAY[]::TEXT[], 'haltere', ARRAY[]::TEXT[], NULL, 'abdomen', ARRAY['Russian twist haltere','Twist russo haltere']::TEXT[], 'free_weight', 'bilateral', 2, 'isolation', 'Sentado com os pés elevados, gire o tronco para os lados segurando um haltere.', 'Usar impulso e girar só os braços.'),
  (NULL, 'Abdominal bicicleta', 'core', ARRAY[]::TEXT[], 'nenhum', ARRAY[]::TEXT[], NULL, 'abdomen', ARRAY['Bicicleta','Bicycle crunch']::TEXT[], 'bodyweight', 'bilateral', 2, 'isolation', 'Deitado, leve o cotovelo em direção ao joelho oposto alternando os lados.', 'Usar impulso e puxar o pescoço.'),
  (NULL, 'Abdominal com rolo', 'core', ARRAY[]::TEXT[], 'outro', ARRAY[]::TEXT[], NULL, 'abdomen', ARRAY['Ab wheel','Rolo abdominal']::TEXT[], 'other', 'bilateral', 3, 'compound', 'De joelhos, role o rolo para frente estendendo o corpo e retorne contraindo o abdômen.', 'Deixar o quadril cair e usar impulso.'),

-- CARDIO (aparelhos)
  (NULL, 'Esteira', 'cardio', ARRAY[]::TEXT[], 'maquina', ARRAY[]::TEXT[], NULL, 'cardio', ARRAY['Esteira','Treadmill']::TEXT[], 'cardio', 'bilateral', 1, 'compound', 'Caminhe ou corra na esteira mantendo a postura ereta.', 'Segurar nos lados e inclinar o tronco.'),
  (NULL, 'Bicicleta ergométrica', 'cardio', ARRAY[]::TEXT[], 'maquina', ARRAY[]::TEXT[], NULL, 'cardio', ARRAY['Bicicleta','Bike']::TEXT[], 'cardio', 'bilateral', 1, 'compound', 'Pedale na bicicleta mantendo a postura ereta.', 'Usar carga excessiva e balançar o tronco.'),
  (NULL, 'Elíptico', 'cardio', ARRAY[]::TEXT[], 'maquina', ARRAY[]::TEXT[], NULL, 'cardio', ARRAY['Elíptico','Elliptical']::TEXT[], 'cardio', 'bilateral', 1, 'compound', 'Mova os pedais e braços em movimento contínuo.', 'Segurar demais nos lados e usar impulso.'),
  (NULL, 'Remo ergométrico', 'cardio', ARRAY[]::TEXT[], 'maquina', ARRAY[]::TEXT[], NULL, 'cardio', ARRAY['Remo','Rowing machine']::TEXT[], 'cardio', 'bilateral', 2, 'compound', 'Puxe a alça em direção ao abdômen estendendo as pernas.', 'Usar impulso e puxar com os ombros.'),
  (NULL, 'Escada ergométrica', 'cardio', ARRAY[]::TEXT[], 'maquina', ARRAY[]::TEXT[], NULL, 'cardio', ARRAY['Escada','Stair climber']::TEXT[], 'cardio', 'bilateral', 2, 'compound', 'Suba degraus em movimento contínuo.', 'Segurar demais nos lados e usar impulso.'),
  (NULL, 'Pular corda', 'cardio', ARRAY[]::TEXT[], 'nenhum', ARRAY[]::TEXT[], NULL, 'cardio', ARRAY['Corda','Jump rope']::TEXT[], 'bodyweight', 'bilateral', 1, 'compound', 'Pule com os pés juntos girando a corda com os punhos.', 'Pular demais e usar os braços.')
ON CONFLICT (name) DO NOTHING;

-- Log do resultado
DO $$
DECLARE
  total_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO total_count FROM public.exercises;
  RAISE NOTICE 'Total exercícios após expansão: %', total_count;
END $$;
